config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "pages#home"
   resources :gears do
    resources :bookings, only: [:create]
   end

   resources :bookings, only: [:index, :destroy]
   get 'my_bookings', to: 'bookings#index', as: 'my_bookings'
   get 'my_gear', to: 'gears#my_gear', as: 'my_gears'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :gear

  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :end_date_after_start_date

  private

  def end_date_after_start_date
    return if end_date.blank? || start_date.blank?

    if end_date < start_date
      errors.add(:end_date, "Must be after the start date")
    end
  end
end

app/models/gear.rb
class Gear < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo

  validates :title, :description, :price_per_day, :category, :availability, presence: true
  validates :price_per_day, numericality: { greater_than_or_equal_to: 0 }

  def owned_by?(user)
    self.user == user
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :gears, dependent: :destroy
  has_many :bookings, dependent: :destroy
end

class Gear < ApplicationRecord
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :store_user_location!, if: :storable_location?

  private

  # Ensure the location is stored if the request is a GET, is not handled by a Devise controller, and is not an Ajax request.
  def storable_location?
    request.get? && is_navigational_format? && !devise_controller? && !request.xhr?
  end

  def store_user_location!
    # Store the location for the user
    store_location_for(:user, request.fullpath)
  end

  # Override Devise method to redirect to stored location after sign-in
  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  # Override Devise method to redirect to stored location after sign-up
  def after_sign_up_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || super
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: %i[first_name last_name])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_booking, only: %i[destroy]

  def create
    @gear = Gear.find(params[:gear_id])
    @booking = @gear.bookings.build(bookings_params)
    @booking.user = current_user
    @booking.total_price = calculate_total_price(@booking)
    if @booking.save
      redirect_to bookings_path
    else
      render 'gears/show', status: :unprocessable_entity
    end
  end

  def index
    @bookings = current_user.bookings.includes(:gear)
  end

  def destroy
    @booking.destroy
    redirect_to bookings_path, status: :see_other
  end

  private

  def bookings_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def calculate_total_price(booking)
    return 0 if booking.start_date.blank? || booking.end_date.blank?

    (booking.end_date - booking.start_date).to_i * booking.gear.price_per_day
  end
end

app/controllers/gears_controller.rb
class GearsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_gear, only: %i[show edit update destroy]

  # GET /gears
  def index
    @gears = Gear.all
  end

  # GET /gears/1
  def show
    @booking = @gear.bookings.build
  end

  # GET /gears/new
  def new
    @gear = Gear.new
  end

  def my_gear
    @gears = current_user.gears
  end

  # POST /gears
  def create
    @gear = Gear.new(gear_params)
    @gear.user_id = current_user.id
    puts "Current user: #{current_user.inspect}"
    if @gear.save
      redirect_to gear_path(@gear)
    else
      puts @gear.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  # GET /gears/1/edit

  def edit
    @gear = Gear.find(params[:id])
  end


  # PATCH/PUT /gears/1
  def update
    if @gear.update(gear_params)
      redirect_to gear_path(@gear)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /gears/1
  def destroy
    @gear.destroy
    redirect_to gears_path, status: :see_other
  end

  private

  def gear_params
    params.require(:gear).permit(:title, :description, :price_per_day, :category, :availability, :photo)
  end

  def set_gear
    @gear = Gear.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @gears = Gear.limit(10) # Adjust the limit as needed
  end
end

app/helpers/application_helper.rb
# app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(flash_type)
    case flash_type.to_sym
    when :notice
      'success'   # Bootstrap class for success messages
    when :alert, :error
      'danger'    # Bootstrap class for error messages
    else
      flash_type.to_s
    end
  end
end

app/views/bookings/index.html.erb
<div class="availible-bikes-advert">
    <div class="page-content-all-gears">

      <!-- Page name and new listing button -->
      <div class="page-header">
        <div class="page-title">My Bookings</div>
        <!-- <div class="button-cell"> <%= link_to 'List Your Bike', new_gear_path, class: 'std-btn' %> </div> -->
      </div>
      <hr />

      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end %>

      <div class="row">
        <% @bookings.each do |booking| %>
          <div class="col-md-4">
            <div class="card mb-4 rounded-4 adver-shadow">

              <% if booking.gear.photo.present? %>
                <div class="bike-view-frame">
                  <%= cl_image_tag(booking.gear.photo.key, class: "booking-view") %>
                </div>
              <%else%>
                <div class="bike-image"></div>
              <%end%>

              <div class="card-body text-center pb-4">
                <p class="card-title fw-bold fs-4"><%= booking.gear.title %></p> <hr />
                <div class="card-view-label">Start Date: <%= booking.start_date %></div>
                <div class="card-view-label">End Date: <%= booking.end_date %></div>
                <div class="card-view-label mb-4">Total Price: <%= booking.total_price %>$</div>
                <%= link_to 'View Bike', gear_path(booking.gear), class: 'std-btn' %>
                <%= form_with model: booking, method: :delete, local: true do |form| %>
                  <%= form.submit 'Cancel Booking', data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to cancel this booking?' }, class: 'std-btn' %>
                <% end %>
              </div>

            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/gears/_form.html.erb
<div class="container">

  <%= form_with(model: @gear, local: true, html: { class: 'row g-3' }) do |form| %>
    <% if @gear.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@gear.errors.count, "error") %> prohibited this gear from being saved:</h2>
        <ul>
          <% @gear.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mb-3">
      <%= form.label :title, class: 'field-label' %>
      <%= form.text_field :title, class: 'form-control', placeholder: 'Enter gear title', value: @gear.title %>
    </div>
      <!--
      <%= form.label :title, class: 'form-label' %>
      <%= form.text_field :title, class: 'form-control', placeholder: 'Enter gear title' %>
      -->


     <div class="mb-3">
      <%= form.label :description, class: 'field-label' %>
      <%= form.text_area :description, class: 'form-control', rows: 6, placeholder: 'Enter description', value: @gear.description %>
     </div>
      <!--
      <%= form.label :description, class: 'form-label' %>
      <%= form.text_area :description, class: 'form-control', rows: 4, placeholder: 'Enter description' %>
      -->


    <div class="row g-3">
      <div class="col-md-6 mb-3">
        <%= form.label :price_per_day, class: 'field-label' %>
        <div class="input-group">
          <span class="input-group-text">£</span>
          <%= form.number_field :price_per_day, class: 'form-control', placeholder: 'Enter price per day', min: 0, value: @gear.price_per_day %>
        </div>
      </div>


    <div class="col-md-6 mb-3" >
      <label class="field-label" for="gear_category">Select Category</label>
      <select class="form-control" name="gear[category]" id="gear_category">
        <option value="Road Bikes" <%= 'selected' if @gear.category == 'Road Bikes' %>>Road Bikes</option>
        <option value="Mountain Bikes" <%= 'selected' if @gear.category == 'Mountain Bikes' %>>Mountain Bikes</option>
        <option value="Electric Bikes" <%= 'selected' if @gear.category == 'Electric Bikes' %>>Electric Bikes</option>
        <option value="Kids' Bikes" <%= 'selected' if @gear.category == "Kids' Bikes" %>>Kids' Bikes</option>
      </select>
    </div>

      <!--
        <%= form.label :category, class: 'field-label' %>
        <%= form.text_field :category, class: 'form-control', placeholder: 'Enter category' %>
      -->




    <div class="content-center">
      <div style="text-align:center;">
        <label class="field-label" style="padding: 0px;" for="gear_availability">Availiable now</label> <br />
        <input class="form-check-input"  type="checkbox" value="1" name="gear[availability]" id="gear_availability" checked>
      </div>
        <!--
        <%= form.label :availability, class: 'form-label' %>
        <%= form.check_box :availability, class: 'form-check-input' %>
        <%= form.label :availability, 'Available', class: 'form-check-label' %>
        -->
    </div>
    <hr />

    <div class="content-center">

      <%= form.file_field :photo %>

      <%= form.submit button_text, class: 'std-btn' %>
    </div>
    <hr />

    <% end %>

    <div class="content-center">
      <%= link_to "Back to all Bikes", gears_path, class: 'std-btn' %>
    </div>
</div>

app/views/gears/edit.html.erb
<div class="content-box-new-gear">
  <div class="page-content">
    <div class="new-gear-container">
      <div class="login-form">
        <p>Edit Bike</p>
          <hr />

            <%= render 'form', button_text: 'Update Bike', gear: @gear %>

      </div>
    </div>
  </div>
</div>

app/views/gears/index.html.erb
  <div class="availible-bikes-advert">
    <div class="page-content-all-gears">

      <!-- Page name and new listing button -->
      <div class="page-header">
        <div class="page-title">Availiable Bikes</div>
        <div class="button-cell"> <%= link_to 'List Your Bike', new_gear_path, class: 'std-btn' %> </div>
      </div>
      <hr />

      <div class="row">
        <% @gears.each do |gear| %>
        <div class="col-md-4">
          <div class="card mb-4 rounded-4 adver-shadow">
            <!-- <div class="bike-image"></div> -->

              <% if gear.photo.present? %>
                <div class="bike-view-frame">
                  <%= cl_image_tag(gear.photo.key, class: "booking-view") %>
                </div>
              <%else%>
                <div class="bike-image"></div>
              <%end%>

              <!-- Verification or user owner -->
              <% if user_signed_in? && gear.owned_by?(current_user) %>
              <div class="msg-at-image">
                <span class="border border-2 border-success fs-4 text-success ps-2 pe-2 rounded-4" style="background-color: #ffffff;">Your Item</span>
              </div>
              <% end %>

              <div class="card-body text-center pb-4">
                <p class="card-title fw-bold fs-4 mb-4"><%= gear.title %></p> <hr />
                <p class="card-text fs-5 mb-4">Price per day: <%= gear.price_per_day %>$</p>
                <!-- <p class="card-text"><strong>Category:</strong> <%= gear.category %></p> -->
                <!-- <p class="card-text"><strong>Availability:</strong> <%= gear.availability ? 'Available' : 'Not Available' %> </p> -->
                <%= link_to 'View Details', gear_path(gear), class: 'std-btn' %>

                <!-- % if user_signed_in? && gear.owned_by?(current_user) % -->
                  <!-- %= link_to 'Edit', edit_gear_path(gear), class: 'btn btn-secondary' % -->
                  <!-- %= link_to 'Delete', gear, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' % -->
                <!-- % end % -->
              </div>

          </div>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/gears/my_gear.html.erb
<div class="availible-bikes-advert">
  <div class="page-content-all-gears">

    <!-- Page name and new listing button -->
    <div class="page-header">
      <div class="page-title">My Bikes</div>
      <div class="button-cell"> <%= link_to 'List Your Bike', new_gear_path, class: 'std-btn' %> </div>
    </div>
    <hr />

<!--
  <h1 class="my-4">My Bikes</h1>
  <%= link_to 'List Your Bike', new_gear_path, class: 'btn btn-success mb-4' %>
-->

      <% if @gears.any? %>
        <div class="row">
          <% @gears.each do |gear| %>
            <div class="col-md-4">
              <div class="card mb-4 rounded-4 adver-shadow">

                <% if gear.photo.present? %>
                  <div class="bike-view-frame">
                    <%= cl_image_tag(gear.photo.key, class: "booking-view") %>
                  </div>
                <%else%>
                  <div class="bike-image"></div>
                <%end%>

                <!-- Verification or user owner -->
                <% if user_signed_in? && gear.owned_by?(current_user) %>
                  <div class="msg-at-image">
                    <span class="border border-2 border-success fs-4 text-success ps-2 pe-2 rounded-4" style="background-color: #ffffff;">Your Item</span>
                  </div>
                <% end %>

                <div class="card-body text-center pb-4">
                <p class="card-title fw-bold fs-4 mb-4"><%= gear.title %></p> <hr />
                <p class="card-text fs-5 mb-4">Price per day: <%= gear.price_per_day %>$</p>
                <!-- <p class="card-text"><strong>Category:</strong> <%= gear.category %></p> -->
                <!-- <p class="card-text"><strong>Availability:</strong> <%= gear.availability ? 'Available' : 'Not Available' %> </p> -->
                <%= link_to 'View Details', gear_path(gear), class: 'std-btn' %>
              </div>

              <!--
                  <h5 class="card-title"><%= gear.title %></h5>
                  <p class="card-text"><strong>Price per day:</strong> £<%= gear.price_per_day %></p>
                  <p class="card-text"><strong>Category:</strong> <%= gear.category %></p>
                  <p class="card-text"><strong>Availability:</strong> <%= gear.availability ? 'Available' : 'Not Available' %></p>
                  <%= link_to 'View', gear_path(gear), class: 'btn btn-primary' %>
                  <%= link_to 'Edit', edit_gear_path(gear), class: 'btn btn-secondary' %>
                  <%= link_to 'Delete', gear, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
              -->

              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <div class="info-window">You have no bikes listed.</div>
      <% end %>
  </div>
</div>

app/views/gears/new.html.erb
<div class="content-box-new-gear">
  <div class="page-content">
    <div class="new-gear-container">
      <div class="login-form">
        <p>List Your Bike</p>
          <hr />

<!--
<h1>New Gear</h1>
-->


        <%= render 'form', button_text: 'List', gear: @gear%>

      </div>
    </div>
  </div>
</div>

app/views/gears/show.html.erb
<div class="availible-bikes-advert">
  <div class="page-content-all-gears">

  <div class="card mt-5 login-form" style="margin: auto;">
    <div class="card-header text-center">
      <div class="page-title">
        <%= @gear.title %>
      </div>
    </div>
    <div class="card-body view-card">

      <!-- Adver image -->
      <div class="view-card-img">
        <% if @gear.photo.present? %>
         <%= cl_image_tag(@gear.photo.key, class: "view-img-full") %>
        <%else%>
          <div class="no-image"></div>
        <% end %>
      </div>

      <!-- Adver Description -->
      <div class="view-card-description">
        <div>
        <!-- <p class="card-text">Category: <%= @gear.category %></p> -->
        <p class="card-view-label">Description:<br />
          <textarea class="card-view-description" rows="7" readonly><%= @gear.description %></textarea>
        </p>
        <hr />

        <p class="card-view-label">Price per day:
          <textarea class="card-view-description" rows="1" readonly><%= @gear.price_per_day %> $</textarea>
        </p>
        <hr />

        <p class="card-view-label">Availability:
          <textarea class="card-view-description" rows="1" readonly><%= @gear.availability ? 'Available' : 'Not Available' %></textarea>
        </p>


        </div>
      </div>
    </div>


    <div class="card-footer">

  <% unless @gear.owned_by?(current_user) %>
    <% if @gear.availability %>
      <div class="card mt-5 login-form">
        <div class="card-view-label text-center">
          <h2>Book This Gear</h2>
          <hr />
        </div>

        <div class="card-body">
          <%= form_with(model: [@gear, @booking], local: true) do |form| %>
            <% if @booking.errors.any? %>
              <div id="error_explanation">
                <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>
                <ul>
                  <% @booking.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <!-- Booking start and end time -->
            <div class="booking-menu">

                <div class="booking-menu-content">
                  <%= form.label :start_date, class: 'card-view-label' %>
                  <%= form.date_field :start_date, class: 'form-control date-picker card-view-description view-select-calendare' %>
                </div>

                <div class="booking-menu-content">
                  <%= form.label :end_date, class: 'card-view-label' %>
                  <%= form.date_field :end_date, class: 'form-control date-picker card-view-description view-select-calendare' %>
                </div>

                <div class="booking-menu-content">
                  <%= form.submit 'Book Now', class: 'std-btn' %>
                </div>
              </div>
          <% end %>

        </div>
      </div>
    <% end %>
  <% end %>
  <br />
  <hr />

    <div class="text-center">
      <% if user_signed_in? && @gear.owned_by?(current_user) %>
        <%= link_to 'Edit', edit_gear_path(@gear), class: 'std-btn' %>
        <%= link_to 'Delete', @gear, method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class: 'std-btn' %>
      <% end %>
      <%= link_to 'Back', gears_path, class: 'std-btn' %>
    </div>
  </div>
  </div>

</div>

</div>
</div>

<script>
document.addEventListener("turbo:load", function() {
  const datePickers = document.querySelectorAll(".date-picker");
  datePickers.forEach(function(datePicker) {
    datePicker.addEventListener("click", function() {
      this.showPicker(); // For modern browsers
      // Alternatively, focus the input if showPicker() is not supported
      this.focus();
    });
  });
});
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RentMyGear</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "home_page", media: 'all', data: { turbolinks: false } %>

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="central-advert">
  <div class="page-content">
    <div class="legenda">
      <p>
        Welcome to BikeShare !
        Discover the freedom of cycling with BikeShare!
      </p>
      <p>Whether you're looking to rent a bike for a day of exploring or
         list your own bike for extra income, our platform offers a seamless
        experience for all cycling enthusiasts.
      </p>
    </div>

    <!-- two buttons not usible -->
    <!--
    <div class="gear-content">
      <div class="gear-box">
        <a class="custom-btn" href="/gears/new">List Your Bike</a>
      </div>

      <div class="gear-box">
        <a class="custom-btn" href="/gears">All Bikes</a>
      </div>
    </div>
    -->

    <div class="best-deals">
      Explore our best deals
    </div>
    <hr />
    <div class="row">
        <% @gears.each do |gear| %>
        <div class="col-md-4">
          <div class="card mb-4 rounded-4 adver-shadow">

              <% if gear.photo.present? %>
                <div class="bike-view-frame">
                  <%= cl_image_tag(gear.photo.key, class: "booking-view") %>
                </div>
              <%else%>
                <div class="bike-image"></div>
              <%end%>

              <!-- Verification or user owner -->
              <% if user_signed_in? && gear.owned_by?(current_user) %>
              <div class="msg-at-image">
                <span class="border border-2 border-success fs-4 text-success ps-2 pe-2 rounded-4" style="background-color: #ffffff;">Your Item</span>
              </div>
              <% end %>

              <div class="card-body text-center pb-4">
                <p class="card-title fw-bold fs-4 mb-4"><%= gear.title %></p> <hr />
                <p class="card-text fs-5 mb-4">Price per day: <%= gear.price_per_day %>$</p>
                <%= link_to 'View Details', gear_path(gear), class: 'std-btn' %>
              </div>

          </div>
        </div>
        <% end %>
      </div>
      <hr /><br />
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<% flash.each do |key, value| %>
  <div class="alert alert-<%= bootstrap_class_for(key) %> alert-dismissible fade show flash-message" role="alert">
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="custom_header">
  <div class="custom_content">
    <div class="top-header">
      <div class="logo">
               <%= image_tag 'logo.png', alt: 'Logo', width: '120px' %>

      </div>
      <span>
          <% if user_signed_in? %>
              <!-- <%= link_to "Home", root_path, class: "nav-link" %> -->
              <!-- <%= link_to "Messages", "#", class: "nav-link" %> -->
            <a href="#" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= image_tag "Mario_avatar.png",class: "avatar-new", alt: "dropdown menu" %>
            </a>
              <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                <%= link_to "Action", "#", class: "dropdown-item item-hided" %>
                <%= link_to "Another action", "#", class: "dropdown-item item-hided" %>
                <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
              </div>
          <% else %>
              <!-- <%= link_to "Login", new_user_session_path, class: "nav-link" %> -->
              <a class="login-btn" href="/users/sign_in">Login</a>
          <% end %>
      </span>
    </div>
  </div>
</div>

<div class="custom-navbar">
  <div class="navbar-content">
    <ul>
      <li> <a href="/">Home</a> </li>
      <li> <a href="/gears">All Bikes</a> </li>
    <% if user_signed_in? %>
      <li><%= link_to 'My Bikes', my_gears_path %></li>
      <li><%= link_to 'My Bookings', my_bookings_path %></li>
      <!-- <li> <a href="#">Messages</a> </li> -->
    <% else %>
      <li> <a href="/users/sign_up">Create Account</a> </li>
    <% end %>
    </ul>
  </div>
</div>